import type { Metadata } from "next";
import { Flowchart, FCNode, FCEdge } from "@/components/ib/flowchart";
import { IconLink, IconShield, IconQuestion } from "@/components/ib/icons";
import { JsonLd, faqPageJsonLd, webPageJsonLd } from "@/components/ib/json-ld";
import { B2Mark, formatB2 } from "@/components/ib/b2-mark";

const TITLE = "B₂ Intelligence";
const DESCRIPTION = "B₂ Intelligence is the intelligence layer for construction supply chains, connecting project, procurement, supplier, logistics and site information so teams can understand disruptions, reason through impact and coordinate action.";
export const metadata: Metadata = { title: TITLE, description: DESCRIPTION, alternates: { canonical: "/b2-intelligence" }, openGraph: { title: TITLE, description: DESCRIPTION, url: "/b2-intelligence" } };

const nodes: FCNode[] = [
  { id: "sources", label: "Project + Supply Data", sub: ["BOQ · RFQ · PO", "schedules · supplier updates"], x: 20, y: 55, w: 230, kind: "source" },
  { id: "b2", label: "B₂ Intelligence", sub: "connect · understand · reason", x: 285, y: 55, w: 210, kind: "twin" },
  { id: "agents", label: "B₂ Agents", sub: ["procurement · logistics", "planning"], x: 535, y: 55, w: 205, kind: "agent" },
  { id: "actions", label: "Coordinated Action", sub: ["recommend · approve", "execute"], x: 785, y: 55, w: 195, kind: "physical" },
];
const edges: FCEdge[] = [{ from: "sources", to: "b2", pulses: 1 }, { from: "b2", to: "agents", pulses: 1 }, { from: "agents", to: "actions", pulses: 1 }];
const faqs = [
  { q: "What is B₂ Intelligence?", a: "B₂ Intelligence is the shared intelligence layer inside Bricks & Brains. It connects fragmented construction and supply-chain information into a contextual model that can understand relationships, evaluate impacts and support coordinated action." },
  { q: "Is B₂ Intelligence another dashboard?", a: "No. Dashboards display information. B₂ Intelligence is designed to connect information, understand dependencies and provide the context B₂ Agents need to reason and act." },
  { q: "What does B₂ connect?", a: "B₂ can connect project schedules, material requirements, procurement records, supplier information, logistics milestones, site updates and carbon data, starting with the data a project already has." },
];

export default function B2Intelligence() {
  return <main>
    <JsonLd data={webPageJsonLd({ name: TITLE, description: DESCRIPTION, path: "/b2-intelligence" })} />
    <JsonLd data={faqPageJsonLd(faqs)} />
    <section className="ib-phero"><div className="ib-grid-bg" /><div className="ib-wrap" style={{ position: "relative" }}><span className="ib-eyebrow">Bricks + Brains</span><h1><B2Mark /> Intelligence</h1><p>The intelligence layer for construction supply chains. <B2Mark /> connects project information, supply-chain data and real-world events into a continuously evolving understanding of construction operations.</p></div></section>
    <section className="ib-sec"><div className="ib-wrap"><div className="ib-head center ib-reveal"><span className="ib-eyebrow ib-idea-eyebrow">The idea</span><h2><span className="ib-idea-bricks-text">Bricks</span> × <span className="ib-idea-brains-text">Brains</span>.</h2><p>The physical construction world connected to the intelligence required to understand and coordinate it.</p></div><div className="ib-idea-grid ib-reveal"><div className="ib-card ib-idea-bricks"><h3>Bricks</h3><p>Projects · Materials · Suppliers · Equipment · Crews · Deliveries · Site conditions</p></div><div className="ib-idea-times" aria-hidden="true">×</div><div className="ib-card ib-idea-brains"><h3>Brains</h3><p>Context · Relationships · Reasoning · Prediction · Decisions · Actions</p></div></div></div></section>
    <section className="ib-sec alt"><div className="ib-wrap"><div className="ib-head center ib-reveal"><span className="ib-eyebrow">Architecture</span><h2>From fragmented information to coordinated action.</h2></div><div className="ib-architecture ib-reveal"><div className="ib-arch-row"><b>01 — Connect</b><p>ERP · Excel · Email · Schedules · BIM · Procurement · Supplier Data</p></div><div className="ib-arch-arrow" aria-hidden="true">↓</div><div className="ib-arch-row"><b>02 — Understand</b><p>Projects ↔ Activities ↔ Materials ↔ Suppliers ↔ Deliveries ↔ Crews ↔ Equipment</p></div><div className="ib-arch-arrow" aria-hidden="true">↓</div><div className="ib-arch-row"><b>03 — Reason</b><p>Understand dependencies · Detect risk · Evaluate alternatives · Predict impact</p></div><div className="ib-arch-arrow" aria-hidden="true">↓</div><div className="ib-arch-row"><b>04 — Act</b><p><B2Mark /> Agents for procurement, planning, logistics, supplier intelligence and carbon.</p></div></div></div></section>
    <section className="ib-sec ib-intelligence-layer"><div className="ib-grid-bg" /><div className="ib-wrap"><div className="ib-head ib-reveal"><span className="ib-eyebrow">The intelligence layer</span><h2>Every project generates knowledge.<br /><span className="cy"><B2Mark /> turns it into intelligence.</span></h2><p>Supplier performance, lead times, substitutions, delivery reliability, project dependencies and carbon information can become reusable organisational context instead of disappearing into spreadsheets and inboxes.</p></div></div></section>
    <section className="ib-sec"><div className="ib-wrap"><div className="ib-head ib-reveal"><span className="ib-eyebrow"><IconLink /> Bricks + Brains</span><h2>Construction has the data. <span style={{ color: "var(--ib-cyan)" }}>It lacks the connections.</span></h2><p>Project information lives across schedules, spreadsheets, emails, procurement systems, supplier documents and people. <B2Mark /> Intelligence turns those fragments into shared construction context.</p></div><Flowchart nodes={nodes} edges={edges} height={260} title="B₂ Intelligence" caption="From fragmented project and supply-chain information to shared context and coordinated action." legend /></div></section>
    <section className="ib-sec"><div className="ib-wrap"><div className="ib-head ib-reveal"><span className="ib-eyebrow"><IconShield /> One shared intelligence layer</span><h2>One brain. <span style={{ color: "var(--ib-cyan)" }}>Multiple <B2Mark /> Agents.</span></h2><p>Procurement, logistics, planning and <B2Mark /> Carbon should not operate from separate versions of the project. <B2Mark /> Intelligence gives specialised agents one connected construction context.</p></div><div className="ib-cards c3"><a className="ib-card" href="/agents/procurement"><h3><B2Mark /> Procurement Agents</h3><p>RFQs, supplier comparisons, risk signals and award preparation.</p></a><a className="ib-card" href="/agents/logistics"><h3><B2Mark /> Logistics Agents</h3><p>Supplier commitments, deliveries, site readiness and disruption response.</p></a><a className="ib-card" href="/b2-carbon"><h3><B2Mark /> Carbon</h3><p>Embodied-carbon intelligence connected directly to material and procurement decisions.</p></a></div></div></section>
    <section className="ib-sec alt"><div className="ib-wrap"><div className="ib-head ib-reveal"><span className="ib-eyebrow"><IconQuestion /> FAQs</span><h2><B2Mark /> Intelligence, answered</h2></div><div className="ib-faq ib-reveal">{faqs.map((f, i) => <details key={i} open={i === 0}><summary>{formatB2(f.q)}</summary><p>{formatB2(f.a)}</p></details>)}</div></div></section>
    <section className="ib-cta"><div className="ib-cta-bg" /><div className="ib-wrap ib-cta-inner"><h2>Give your project a <span className="cy">shared intelligence layer.</span></h2><p>Start with one project or material workflow using the data your team already has.</p><div className="ib-cta-actions"><a href="/contact-us" className="ib-btn ib-btn-ghost">Talk to Bricks &amp; Brains</a></div></div></section>
  </main>;
}
